[project]
name = "penny-track"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirer>=3.4.0",
    "rich>=14.0.0",
    "sqlalchemy>=2.0.40",
]
